version: '3.8'

services:
  db:
    image: postgres:15
    container_name: cee-sc-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ceesc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cee-sc-network

  api:
    build: ../backend
    container_name: cee-sc-api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ceesc?schema=public
      - PORT=3001
      - HOST=0.0.0.0
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../backend:/app
      - /app/node_modules
    networks:
      - cee-sc-network
    command: npm run dev

  web:
    build: ../frontend
    container_name: cee-sc-web
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - cee-sc-network
    command: npm run dev

volumes:
  pgdata:

networks:
  cee-sc-network:
    driver: bridge
